"use client";

import Link from "next/link";
import { useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { Navbar } from "@/components/Navbar";

const opportunities = [
  { token: "$ORBIT", pair: "ORBIT / SOL", age: "38s", liquidity: "$284K", score: "94", status: "ARMED", color: "#d4a646" },
  { token: "$MIRA", pair: "MIRA / SOL", age: "2m", liquidity: "$91K", score: "87", status: "WATCH", color: "#afc3a0" },
  { token: "$KITE", pair: "KITE / SOL", age: "4m", liquidity: "$612K", score: "82", status: "WATCH", color: "#c8a7a0" },
];

export default function HomePage() {
  const { connected } = useWallet();
  return <>
    <Navbar />
    <main className="overflow-hidden bg-[#15130f] text-[#f4ecdb]">
      <section className="border-b border-[#5a4a30]">
        <div className="mx-auto max-w-7xl px-6 pb-20 pt-12 sm:pb-28 sm:pt-20">
          <div className="flex items-center justify-between border-b border-[#5a4a30]/60 pb-4 font-mono text-[9px] uppercase tracking-[.22em] text-[#a6987d]"><span>AURA / private capital desk</span><span className="hidden sm:block">Solana mainnet · ledger 312,847,190</span></div>
          <div className="grid items-center gap-14 pt-14 lg:grid-cols-[1.08fr_.92fr] lg:gap-24">
            <div>
              <p className="font-mono text-[10px] uppercase tracking-[.25em] text-[#d4a646]">The autonomous sniper, refined</p>
              <h1 className="engraved mt-5 max-w-3xl font-display text-5xl leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[88px]">A quieter way<br /><em className="text-[#d4a646]">to move early.</em></h1>
              <p className="mt-7 max-w-xl text-base leading-8 text-[#a6987d] sm:text-lg">AURA reads new Solana launches like a private market desk: patiently, selectively, and with every risk gate recorded before capital moves.</p>
              <div className="mt-9 flex flex-col gap-3 sm:flex-row">{connected ? <Link href="/dashboard" className="inline-flex items-center justify-center gap-3 rounded-sm border border-[#e1b95e] bg-[#d4a646] px-6 py-4 font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#21180b] transition hover:bg-[#edc873]">Open the ledger <span aria-hidden="true">→</span></Link> : <div className="[&_.wallet-adapter-button]:!h-12 [&_.wallet-adapter-button]:!rounded-sm"><WalletMultiButton /></div>}<a href="#ledger" className="inline-flex items-center justify-center rounded-sm border border-[#6e5930] px-6 py-4 font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#d8c9a8] transition hover:border-[#d4a646] hover:text-[#d4a646]">Read the signals</a></div>
              <div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 font-mono text-[9px] uppercase tracking-[.15em] text-[#8f8168]"><span><b className="text-[#d4a646]">●</b> non-custodial</span><span><b className="text-[#afc3a0]">●</b> paper-first</span><span><b className="text-[#c8a7a0]">●</b> Jupiter routed</span></div>
            </div>
            <div className="ledger-surface relative mx-auto w-full max-w-[450px] border border-[#6e5930] p-5 shadow-[0_18px_60px_rgba(0,0,0,.28)]" aria-label="AURA scanner visualization"><div className="border border-[#6e5930]/80 p-6"><div className="flex items-center justify-between font-mono text-[9px] uppercase tracking-[.17em] text-[#a6987d]"><span>Signal ledger</span><span className="text-[#d4a646]">Live</span></div><div className="relative my-10 aspect-square rounded-full border border-[#6e5930] bg-[#15130f]"><div className="absolute inset-[16%] rounded-full border border-dashed border-[#d4a646]/45" /><div className="absolute inset-[33%] rounded-full border border-[#afc3a0]/30" /><div className="absolute left-1/2 top-1/2 h-px w-[90%] -translate-x-1/2 bg-[#6e5930]" /><div className="absolute left-1/2 top-1/2 h-[90%] w-px -translate-x-1/2 bg-[#6e5930]" /><div className="absolute left-[20%] top-[29%] size-2 rounded-full bg-[#d4a646] shadow-[0_0_14px_#d4a646]" /><div className="absolute bottom-[25%] right-[20%] size-2 rounded-full bg-[#afc3a0] shadow-[0_0_14px_#afc3a0]" /><div className="absolute left-1/2 top-1/2 flex size-28 -translate-x-1/2 -translate-y-1/2 flex-col items-center justify-center rounded-full border border-[#d4a646] bg-[#211d16] text-center"><span className="font-mono text-[8px] uppercase tracking-[.2em] text-[#a6987d]">system</span><strong className="mt-1 font-display text-2xl text-[#d4a646]">ARMED</strong><span className="font-mono text-[8px] text-[#afc3a0]">94.2% ready</span></div></div><div className="grid grid-cols-3 gap-3 border-t border-[#5a4a30] pt-4 font-mono text-[9px] uppercase tracking-[.12em] text-[#8f8168]"><span>38,421<br /><b className="text-[#d8c9a8]">scans</b></span><span>1,284<br /><b className="text-[#d8c9a8]">new pools</b></span><span>04<br /><b className="text-[#d8c9a8]">armed</b></span></div></div></div>
          </div>
        </div>
      </section>
      <section className="border-b border-[#5a4a30] bg-[#211d16] py-3"><div className="mx-auto flex max-w-7xl items-center gap-6 overflow-hidden px-6 font-mono text-[9px] uppercase tracking-[.16em] text-[#a6987d]"><span className="shrink-0 text-[#d4a646]">Market register</span><span className="shrink-0">SOL <b className="text-[#afc3a0]">+2.84%</b></span><span className="shrink-0">JUP <b className="text-[#afc3a0]">+6.10%</b></span><span className="shrink-0">RAY <b className="text-[#afc3a0]">+3.42%</b></span><span className="hidden shrink-0 sm:inline">1,284 new pools</span><span className="hidden shrink-0 md:inline">38,421 scans today</span></div></section>
      <section id="ledger" className="mx-auto max-w-7xl px-6 py-20 sm:py-28"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[9px] uppercase tracking-[.22em] text-[#d4a646]">/ the signal ledger</p><h2 className="mt-3 font-display text-4xl tracking-[-.04em] sm:text-5xl">What the desk sees.</h2></div><p className="max-w-sm font-mono text-xs leading-6 text-[#a6987d]">Every pool enters the register. Only evidence moves it from observed to armed.</p></div><div className="overflow-hidden border border-[#6e5930] bg-[#211d16]"><div className="flex items-center justify-between border-b border-[#5a4a30] px-4 py-3 font-mono text-[9px] uppercase tracking-[.16em] text-[#a6987d]"><span>Signal register / block 198,442,761</span><span className="text-[#d4a646]">refresh 2s</span></div>{opportunities.map((item) => <div key={item.token} className="grid gap-3 border-b border-[#5a4a30] px-5 py-4 last:border-b-0 sm:grid-cols-[1.3fr_1fr_.7fr_1fr_.6fr_.7fr] sm:items-center"><div><div className="flex items-center gap-2 font-mono text-sm font-bold"><span className="size-2 rounded-full" style={{ background: item.color }} />{item.token}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[.14em] text-[#8f8168]">{item.pair}</div></div><span className="font-mono text-xs text-[#a6987d]">{item.age} · {item.liquidity}</span><span className="font-mono text-xs uppercase text-[#a6987d]">liquidity clear</span><strong className="font-mono text-lg" style={{ color: item.color }}>{item.score}</strong><span className="w-fit border px-2 py-1 font-mono text-[9px] font-bold tracking-[.12em]" style={{ color: item.color, borderColor: `${item.color}88` }}>{item.status}</span></div>)}</div></section>
      <section className="border-y border-[#5a4a30] bg-[#211d16]"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-20 sm:py-28 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="font-mono text-[9px] uppercase tracking-[.22em] text-[#d4a646]">/ execution protocol</p><h2 className="mt-4 font-display text-4xl tracking-[-.04em] sm:text-5xl">Speed in hand.<br /><em className="text-[#a6987d]">Patience in policy.</em></h2><p className="mt-6 max-w-md text-sm leading-7 text-[#a6987d]">AURA is a layered gate, not a buy button with a robot attached. The desk refuses to trade when the evidence is incomplete.</p></div><div className="grid gap-3 sm:grid-cols-2">{[{ n:"01", t:"Observe", d:"New pools and wallet flow enter the register." },{ n:"02", t:"Appraise", d:"Liquidity, momentum, holders, and velocity become one signal." },{ n:"03", t:"Protect", d:"Safety, slippage, limits, and simulation run first." },{ n:"04", t:"Execute", d:"Paper or live. Jupiter routes only after every gate clears." }].map((step) => <div key={step.n} className="border border-[#6e5930] p-5"><span className="font-mono text-[10px] text-[#d4a646]">{step.n}</span><h3 className="mt-7 font-display text-xl">{step.t}</h3><p className="mt-2 text-sm leading-6 text-[#a6987d]">{step.d}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-4xl px-6 py-24 text-center sm:py-32"><p className="font-mono text-[9px] uppercase tracking-[.22em] text-[#d4a646]">/ open a private desk</p><h2 className="mt-4 font-display text-4xl tracking-[-.05em] sm:text-6xl">Trade less noise.<br /><em className="text-[#d4a646]">Keep more signal.</em></h2><p className="mx-auto mt-6 max-w-xl text-sm leading-7 text-[#a6987d]">Connect a wallet. Begin in paper mode. Let AURA prove the edge before capital is ever deployed.</p>{connected ? <Link href="/dashboard" className="mt-9 inline-flex items-center gap-3 rounded-sm border border-[#e1b95e] bg-[#d4a646] px-6 py-4 font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#21180b]">Enter the desk <span aria-hidden="true">→</span></Link> : <div className="mt-9 inline-block [&_.wallet-adapter-button]:!h-12 [&_.wallet-adapter-button]:!rounded-sm"><WalletMultiButton /></div>}</section>
    </main>
    <footer className="flex flex-col gap-4 border-t border-[#5a4a30] bg-[#15130f] px-6 py-8 font-mono text-[9px] uppercase tracking-[.15em] text-[#8f8168] sm:flex-row sm:items-center sm:justify-between"><div className="font-display text-sm normal-case tracking-normal text-[#f4ecdb]">AutoSave <span className="text-[#d4a646]">/ AURA</span></div><div>Solana-only · non-custodial · © 2026</div><a href="https://github.com/lilcoins89/autosave" target="_blank" rel="noreferrer" className="transition hover:text-[#d4a646]">Source ↗</a></footer>
  </>;
}
